# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registrationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmeta',
            name='rule_tests_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
